WebApi/Controllers/HomeController.cs
using Application.DTOs;
using Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Web.Helpers;
using WebApi.ViewsModel;
using static System.Reflection.Metadata.BlobBuilder;
using RegistrationForm = WebApi.ViewsModel.RegistrationForm;

namespace WebApi.Controllers
{
    public class HomeController : Controller
    {
        //private readonly MyDbContext _dbContext;
        //private readonly HttpClient _httpClient;
        private readonly IHttpClientFactory _httpClientFactory;
        //private IHttpClientFactory httpClientFactory;
        //private readonly ImageFileMachine passportPhotograph;
        private readonly IFormFile passportPhotograph;

        public HomeController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        public async Task<IActionResult> Index()
        {
            //var response = await _httpClient.GetAsync("https://localhost:7003/api/RegistrationForm");
            var httpClient = _httpClientFactory.CreateClient();
            var response = await httpClient.GetAsync("https://localhost:7003/api/RegistrationForm");
            response.EnsureSuccessStatusCode();
            var responseBody = await response.Content.ReadAsStringAsync();
            var myData = JsonSerializer.Deserialize<List<Registration>>(responseBody);
            // Process the response body
            return View(myData);
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}

        //public IActionResult Delete(int? userId)
        public async Task<IActionResult> DeleteGet(int? userId)
        {

            if (userId == null)
            {
                //Console.WriteLine(1010);
                return NotFound();
            }
            var httpClient = _httpClientFactory.CreateClient();
            var response = await httpClient.GetAsync($"https://localhost:7003/api/RegistrationForm/{userId}");
            //Console.WriteLine(response.StatusCode);
            //Console.WriteLine(response);
            if (response.IsSuccessStatusCode)
            {
                var registration = await response.Content.ReadFromJsonAsync<Registration>();
                return View("Delete",registration);
            }
            else
            {
                Console.WriteLine(5050);
                return NotFound();
            }
            //return View();
            // retrieve your registration model here
            //var registration = Registration
            //return View("Delete", registration);
            //return View("~/Views/Home/Delete.cshtml");
            //return View("~/Views/Home/Edit.cshtml");
        }


        public async Task <IActionResult> EditGet(int? userId)
        {
            if (userId == null)
            {
                return NotFound();
            }
            var httpClient = _httpClientFactory.CreateClient();
            var response = await httpClient.GetAsync($"https://localhost:7003/api/RegistrationForm/{userId}");
            if (response.IsSuccessStatusCode)
            {
                var registration = await response.Content.ReadFromJsonAsync<Registration>();
                return View("Edit", registration);
            }
            else
            {
                return NotFound();
            }
  
            //return View("~/Views/Home/Edit.cshtml");
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int? userId, Registration registration)
        {
            if (userId == null)
            {
                return NotFound();
            }
            Console.WriteLine($"checkb4code: " + registration);

            if (ModelState.IsValid)
            {
                // Map Registration object properties to UpdateRegistrationFormDto properties
                //var updateRegistrationFormDto = new UpdateRegistrationFormDto
                //{
                //    UserId = registration.userId,
                //    FullName = registration.fullName,
                //    Email = registration.email,
                //    Password = registration.password,
                //    ConfirmPassword = registration.password,
                //    // ConfirmPassword = registration.confirmPassword, // Uncomment if confirmPassword is available in Registration model
                //    PassportPhotograph = passportPhotograph
                //};

                var httpClient = _httpClientFactory.CreateClient();
                Console.WriteLine($"check " + registration);
                //var json = JsonSerializer.Serialize(updateRegistrationFormDto);
                ////var json = JsonSerializer.Serialize(registration);
                //var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await httpClient.PutAsync($"https://localhost:7003/api/RegistrationForm?UserId={userId}&FullName={registration.fullName}&Email={registration.email}&Password={registration.password}&ConfirmPassword={registration.password}", null);
                //var response = await httpClient.PutAsync($"https://localhost:7003/api/RegistrationForm?userId={userId}", content);
                //var response = await httpClient.PutAsync($"https://localhost:7003/api/RegistrationForm/{userId}", content);
                //'https://localhost:7003/api/RegistrationForm?UserId=1&FullName=striooppng%201&Email=sjn%40ing.vb&Password=str000ing1&ConfirmPassword=str000ing1'

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Failed to update registration.");
                }
            }

            return View("Edit");
            //return View("Edit", registration);
        }


        public async Task <IActionResult> DetailGet(int? userId)
        {
            if (userId == null)
            {
                return NotFound();
            }
            var httpClient = _httpClientFactory.CreateClient();
            var response = await httpClient.GetAsync($"https://localhost:7003/api/RegistrationForm/{userId}");
            if (response.IsSuccessStatusCode)
            {
                var registration = await response.Content.ReadFromJsonAsync<Registration>();
                return View("Detail", registration);
            }
            else
            {
                return NotFound();
            }
            //return View("~/Views/Home/Detail.cshtml");
        }


        [HttpGet]
        public async Task<IActionResult> OnGetAsync(int? userId)
        {
            if (userId == null)
            {
                return RedirectToAction("Index");
                //return RedirectToAction("Index", "Home");
            }
            var httpClient = _httpClientFactory.CreateClient();
            var response = await httpClient.GetAsync("https://localhost:7003/api/RegistrationForm");
            response.EnsureSuccessStatusCode();
            var responseBody = await response.Content.ReadAsStringAsync();
            var myData = JsonSerializer.Deserialize<List<Registration>>(responseBody);
            var registrations = myData.FirstOrDefault(e => e.userId == userId);

            if (registrations == null)
            {
                return RedirectToAction("Index");
            }
            else
            {

                // Assuming RegistrationForm or similar
                var viewModel = new RegistrationForm
                {
                    Registration = registrations
                };
                return View(viewModel);
                //Registration = registrations;
                //return View("Index");
            }
        }

        //public async Task<IActionResult> OnPostAsync(int? userId)?
        [HttpPost]
        public async Task<IActionResult> Delete(int? userId)
        {
            if (userId == null)
            {
                return View();
            }

            //var registrationForms = await context.RegistrationForm.FindAsync(id);
            var httpClient = _httpClientFactory.CreateClient();
            //var response = await httpClient.GetAsync("https://localhost:7003/api/RegistrationForm");
            //response.EnsureSuccessStatusCode();
            //var responseBody = await response.Content.ReadAsStringAsync();
            //var myData = JsonSerializer.Deserialize<List<Registration>>(responseBody);
            //var registration = myData.FirstOrDefault(e => e.userId == userId);

            //if (registration == null)
            //{
            //    return View();
            //}
            //else
            //{
                try
                {
                var deleteResponse = await httpClient.DeleteAsync($"https://localhost:7003/api/RegistrationForm?id={userId}");
                deleteResponse.EnsureSuccessStatusCode();

                    return RedirectToAction("Index");
                }

                catch (HttpRequestException ex)
                    {
                        if (ex.InnerException != null)
                        {
                            Console.WriteLine($"Inner exception: {ex.InnerException.Message}");
                            return StatusCode((int)HttpStatusCode.InternalServerError);
                        }
                        else
                        {
                            Console.WriteLine($"Error: {ex.Message}");
                            return StatusCode((int)HttpStatusCode.InternalServerError);
                        }
                    }

            //catch (HttpRequestException ex)
            //    {
            //    var responseContent = await ex.Response.Content.ReadAsStringAsync();

WebApi/Controllers/RegistrationViewController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.Security.Principal;
using WebApi.ViewsModel;

namespace WebApi.Controllers
{
    public class RegistrationViewController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}
        public RegistrationForm registrationForm { get; set; }

        public void OnGet()
        {
        }

        public class AllowedFileExtensionsAttribute : ValidationAttribute
        {
            private readonly string[] _allowedExtensions;

            public AllowedFileExtensionsAttribute(string[] allowedExtensions)
            {
                _allowedExtensions = allowedExtensions;
            }

            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                var file = value as IFormFile;
                if (file != null)
                {
                    // Access the object
                    var fileExtension = Path.GetExtension(file.FileName).ToLower();

                    if (!_allowedExtensions.Contains(fileExtension))
                    {
                        return new ValidationResult("Only .jpg and .png files are allowed");
                    }

                    return ValidationResult.Success;
                }
                else
                {
                    return ValidationResult.Success;


                }
                   
            }
        }


        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(RegistrationForm registrationForm)
        {
            if (!ModelState.IsValid)
            {
                System.Console.WriteLine(100);
                return View(registrationForm);
            }

            try
            {
                var httpClient = new HttpClient();
                
                if (!ModelState.IsValid)
                {
                    foreach (var modelStateKey in ModelState.Keys)
                    {
                        var modelStateVal = ModelState[modelStateKey];
                        foreach (var error in modelStateVal.Errors)
                        {
                            Console.WriteLine(error);
                            Console.WriteLine($"Error: {error.ErrorMessage}");
                        }
                    }
                }
                Console.WriteLine(JsonConvert.SerializeObject(registrationForm));
                
                //var response = await httpClient.PostAsJsonAsync("https://localhost:7003/api/RegistrationForm", registrationForm);
                var content = new MultipartFormDataContent();
                content.Add(new StringContent(registrationForm.FullName), "FullName");
                content.Add(new StringContent(registrationForm.Email), "Email");
                content.Add(new StringContent(registrationForm.Password), "Password");
                content.Add(new StringContent(registrationForm.ConfirmPassword), "ConfirmPassword");
                //content.Add(new StreamContent(File.OpenRead("path/to/file")), "PassportPhotograph", "file.name");

                var response = await httpClient.PostAsync("https://localhost:7003/api/RegistrationForm", content);

                if (response.IsSuccessStatusCode)
                {
                    //System.Console.WriteLine(registrationForm);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error occurred while processing your request.");
                    var errorContent = await response.Content.ReadAsStringAsync();
                    // Log or display the error content
                    return View(registrationForm);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
                return View(registrationForm);
            }
        }
    }
}

WebApi/Views/Home/Delete.cshtml
@* @model WebApi.Views.Home.DeleteModel *@
@model WebApi.ViewsModel.Registration
@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure that you want to delete this?</h3>

<div>
    <dl class="row">
        <dt class="col-2">
            @* @Html.DisplayNameFor(model => model.Books.BookTitle) *@
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.userId)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.fullName)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.fullName)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.email)
        </dd>
    </dl>

    <form method="post" asp-action="Delete">
    @* <form method="post" asp-action="OnPostAsync"> *@
        <input type="hidden" asp-for="userId" />
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary">Back</a>
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

WebApi/Views/Home/Detail.cshtml
@* @model WebApi.Views.Home.DeleteModel *@
@model WebApi.ViewsModel.Registration
@{
    ViewData["Title"] = "Detail";
}

<h1>Details</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.userId)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.fullName)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.fullName)
        </dd>
        <dt class="col-2">
            @Html.DisplayNameFor(model => model.email)
        </dt>
        <dd class="col-10">
            @Html.DisplayFor(model => model.email)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Home" asp-action="Index" class="btn btn-danger">Back</a>
    <a  asp-action="EditGet" asp-route-userId="@Model.userId" class="btn btn-primary">Edit</a>
</div>

WebApi/Views/Home/Edit.cshtml
@* @model WebApi.Views.Home.DeleteModel *@
@model WebApi.ViewsModel.Registration
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<hr />

<div class="row">
    <div class="col-4">
        <form method="post" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="userId" />

            <div class="form-group">
                    <label asp-for="fullName" class="control-label"></label>
                    <input asp-for="fullName" class="form-control" />
                    <span asp-validation-for="fullName" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                    <label asp-for="email" class="control-label"></label>
                    <input asp-for="email" class="form-control" />
                    <span asp-validation-for="email" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <label asp-for="password" class="control-label"></label>
                <input asp-for="password" class="form-control" />
                <span asp-validation-for="password" class="text-danger"></span>
            </div>            
            @* <div class="form-group mt-2">
                <label asp-for="confirmPassword" class="control-label"></label>
                <input asp-for="confirmPassword" class="form-control" />
                <span asp-validation-for="confirmPassword" class="text-danger"></span>
            </div> *@
            <div class="form-group mt-2">
                <label asp-for="passportPhotograph" class="control-label"></label>
                <input asp-for="passportPhotograph" class="form-control" type="file" />
                <span asp-validation-for="passportPhotograph" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <a asp-controller="Home" asp-action="Index" class="btn btn-danger">Back</a>
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebApi/Views/Home/Index.cshtml
  @*   For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860 *@


@model IEnumerable<WebApi.ViewsModel.Registration>
@{
    ViewData["Title"] = "Home Page";
}
<h1>Welcome to MVC!</h1>
<h3>ASP.NET MVC with Razor Views</h3>
<hr />
<div class="text-center">
    <h1 class="display-4">Mike</h1>
    <p>Test-Part1 <a href="https://github.com/mikeolams">building Web apps with ASP.NET Core to fulfill ASP.NET MVC (with Razor Views) and Web API requirement </a>.</p>
</div>
 @* System.Console.WriteLine(_name); *@
<a asp-controller="RegistrationView" class="btn btn-success float-end">Register</a>
<table class="table table-responsive table-striped table-hover align-middle">
    <thead>
        <tr class="text-center">
                <th>UserId</th>
                <th>FullName</th>
                <th>Email</th>
                <th>Password</th>
                <th>PassportPhotograph</th>
                @* <th>@Html.DisplayNameFor(model => model.PassportPhotograph)</th> *@
            <th>Actions</th>
        </tr>
        @* <tr class="text-center">
            <th>@Html.DisplayNameFor(model => model.Registration[0].userId)</th>
            <th>@Html.DisplayNameFor(model => model.Registration[0].userId)</th>
            <th>@Html.DisplayNameFor(model => model.Registration[0].userId)</th>
            <th>Actions</th>
        </tr> *@
    </thead>
    <tbody>
        @foreach (var registration in Model)
        {
            @* Console.WriteLine(registration); *@
            <tr class="text-center">
                    <td>@Html.DisplayFor(model => registration.userId)</td>
                    <td>@Html.DisplayFor(model => registration.fullName)</td>
                    <td>@Html.DisplayFor(model => registration.email)</td>
                    <td>@Html.DisplayFor(model => registration.password)</td>
                    <td>@Html.DisplayFor(model => registration.passportPhotograph)</td>
                @* <td>@Html.DisplayFor(model => registration.userId)</td>
                <td>@Html.DisplayFor(model => registration.fullName)</td>
                <td>@Html.DisplayFor(model => registration.email)</td>
                <td>@Html.DisplayFor(model => registration.password)</td>asp-action="Delete" asp-route-userId="@Model.userId"
                <td>@Html.DisplayFor(model => registration.passportPhotograph)</td> *@
                <td>
                    <a asp-controller="Home" asp-action="EditGet" asp-route-userId="@registration.userId" class="btn btn-primary">Edit</a>
                    <a asp-controller="Home" asp-action="DetailGet" asp-route-userId="@registration.userId" class="btn btn-success">Details</a>
                    <a asp-controller="Home" asp-action="DeleteGet" asp-route-userId="@registration.userId" class="btn btn-danger">Delete</a>
                    @* <a asp-controller="Delete" asp-route-id="@registration.userId" class="btn btn-danger">Delete</a> *@
                </td>
            </tr>
        }
    </tbody>
</table>